---
name: Build and test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: srt32/hugo-action@master
      - uses: chabad360/htmlproofer@v2
        with:
          directory: ./public
          arguments: --check-sri --only-4xx
